logging:
  file:
    name: logs/authentication.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.authentication: debug

spring:
  config:
    import:
      - classpath:/config/datasource-local.yml

# 마이크로서비스 등록
eureka:
  instance:
    prefer-ip-address: true                                                          # IP주소를 이용하여 eureka 서버등록
  client:
    register-with-eureka: true                                                       # eureka에 등록여부
    fetch-registry: true                                                             # registry에 저장된 내용을 캐시해서 출력여부
    service-url:
      defaultZone: http://localhost:8761/eureka/