spring:
  datasource:
    driver-class-name: com.mariadb.jdbc.Driver
    url: jdbc:mysql://mariadb:3306/msa?characterEncoding=UTF-8
    username: root
    password: '{cipher}1c13d3d57913637a9b6a5cb54656f2a9b6055e6a12c70b100e76ee7e14c87a29'
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      format_sql: true
      ddl-auto: create